name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Android App
        run: |
          npm install --legacy-peer-deps
          [ -f "www/capacitor.config.json" ] && cp www/capacitor.config.json .
          
          # যদি android ফোল্ডার না থাকে তবেই যোগ করবে
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          
          npx cap sync
          
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
